<a href="https://colab.research.google.com/github/LIvanoff/recommend-postamate/blob/master/pr2_ropsppr.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Модельные методы рекомендательных системнаосновесингулярного разложения

Cоздать программную реализацию модельногометодарекомендательной системы (РС), основанную на сингулярномразложенииикластерном анализе и включающую:
- актуальную предметную область для применения РС (вродемаркетплейса, медиа ресурсов, соц. сетей, экономической сферыит.д.)инабор начальных данных для неё (опрос покупателей, статистка за временной период и т.д., см. Примечание 1);
- привести входные данные к матричному виду для выполненияеёсингулярного разложения вида A = UDV
T и получения на его основе предпочтений пользователей, характеристики объектов и сингулярных значений как значимость воздействия факторов на пользователей,интерпретировать эти факторы для человеческого восприятия (см.Примечание 2);
- произвести измерение качества рекомендаций на основеметриккачества (вроде MSE, MAE и т.д.) и реальных оценок полученных пользователями рекомендаций;
- выполнить кластеризацию пользователей или их рекомендаций(результатов предыдущих пунктов задания) с помощью EM-алгоритма или иерархической кластеризации;

In [ ]:
!pip install https://github.com/explosion/spacy-models/releases/download/ru_core_news_sm-3.1.0/ru_core_news_sm-3.1.0.tar.gz

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import nltk
# from nltk.tokenize import word_tokenize
import spacy
from spacy import load
from spacy.lang.ru.examples import sentences
from spacy.lang.ru import Russian
from nltk.corpus import stopwords

In [ ]:
# nltk.download('punkt')

In [ ]:
file = open("bts.txt")
text = ' '.join(file.read().splitlines())
text

'Сегодня мы стоим на пороге рассвета беспилотных технологий. Чтобы понять, что нас ожидает в будущем, необходимо обратиться к истории, с чего мы и начнем. Начало развития информационных технологий приходится на 1960-е, когда Fairchild Semiconductors и Intel заложили их фундамент, выпустив первые в мире микропроцессоры, а в качестве побочного продукта основав Кремниевую долину. Однако, несмотря на то что микропроцессорные технологии обеспечивали значительный прирост производительности, они были недоступны для широкого применения. В 1980-х годах Microsoft и Apple заложили фундамент второго этапа развития информационных технологий, представив графический пользовательский интерфейс и реализовав концепцию «ПК/Mac в каждом доме». В 2000-х интернет-компании под эгидой Google дали старт третьему этапу, связав людей и информацию, т. е. обеспечили потенциальную связь между источниками и потребителями информации. Затем в 2010-х создатели социальных сетей, таких как Facebook и LinkedIn, положили н

In [ ]:
text = re.sub("[A-Za-z0-9!#$%&()*+,./:;«»<=>?@[\]^_`{|}~—–\\-]+", '', text)
text = text.split()

Произведём лемматизацию

In [ ]:
nlp = Russian()
load_model = load("ru_core_news_sm")
nltk.download('stopwords')
stopwords_ru = stopwords.words("russian")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
stopwords_ru.append('е')
stopwords_ru.append('т')
stopwords_ru.append('х')
stopwords_ru.append('ба')
stopwords_ru.append('±')
stopwords_ru.append('°')
stopwords_ru.append('х')
stopwords_ru.append('×')
stopwords_ru.append('θ')

In [ ]:
lemma = []

for doc in load_model.pipe(text):
  for word in doc:
    lemma.append(word.lemma_)

In [ ]:
text = ' '.join(lemma)

Удаляем стоп-слова

In [ ]:
tokens = []
for token in text.split():
  if token not in stopwords_ru:
    tokens.append(token)

In [ ]:
words = list(set(tokens))
len(words)

1971

In [ ]:
df = pd.DataFrame(0, index=words, columns=words)
df

распределить  временны́е  двухчастотного  изображение  \
распределить               0           0               0            0   
временны́е                 0           0               0            0   
двухчастотного             0           0               0            0   
изображение                0           0               0            0   
умолчание                  0           0               0            0   
...                      ...         ...             ...          ...   
таковая                    0           0               0            0   
горизонтальный             0           0               0            0   
окклюзия                   0           0               0            0   
транспортный               0           0               0            0   
высокий                    0           0               0            0   

                умолчание  прогнозирование  фильтров  ввиду  выдвигать  \
распределить            0                0         0      0          0   
временны́е              0                0         0      0          0   
двухчастотного          0                0         0      0          0   
изображение             0                0         0      0          0   
умолчание               0                0         0      0          0   
...                   ...              ...       ...    ...        ...   
таковая                 0                0         0      0          0   
горизонтальный          0                0         0      0          0   
окклюзия                0                0         0      0          0   
транспортный            0                0         0      0          0   
высокий                 0                0         0      0          0   

                расстояние  ...  ключевой  сеть  хотя  спутнико  отключение  \
распределить             0  ...         0     0     0         0           0   
временны́е               0  ...         0     0     0         0           0   
двухчастотного           0  ...         0     0     0         0           0   
изображение              0  ...         0     0     0         0           0   
умолчание                0  ...         0     0     0         0           0   
...                    ...  ...       ...   ...   ...       ...         ...   
таковая                  0  ...         0     0     0         0           0   
горизонтальный           0  ...         0     0     0         0           0   
окклюзия                 0  ...         0     0     0         0           0   
транспортный             0  ...         0     0     0         0           0   
высокий                  0  ...         0     0     0         0           0   

                таковая  горизонтальный  окклюзия  транспортный  высокий  
распределить          0               0         0             0        0  
временны́е            0               0         0             0        0  
двухчастотного        0               0         0             0        0  
изображение           0               0         0             0        0  
умолчание             0               0         0             0        0  
...                 ...             ...       ...           ...      ...  
таковая               0               0         0             0        0  
горизонтальный        0               0         0             0        0  
окклюзия              0               0         0             0        0  
транспортный          0               0         0             0        0  
высокий               0               0         0             0        0  

[1971 rows x 1971 columns]

In [ ]:
range_ = [2, 1, -1, -2]
for i, word in enumerate(tokens):
  if i == 0:
    df.loc[word, tokens[i + 1]] += 1
    df.loc[word, tokens[i + 2]] += 1
  elif i == 1:
    df.loc[word, tokens[i - 1]] += 1
    df.loc[word, tokens[i + 1]] += 1
    df.loc[word, tokens[i + 2]] += 1
  elif i == len(tokens) - 2:
    df.loc[word, tokens[i - 2]] += 1
    df.loc[word, tokens[i - 1]] += 1
    df.loc[word, tokens[i + 1]] += 1
  elif i == len(tokens) - 1:
    df.loc[word, tokens[i - 2]] += 1
    df.loc[word, tokens[i - 1]] += 1
  else:
    for j in range_:
      df.loc[word, tokens[i - j]] += 1

for i in range(len(tokens)):
  if df.loc[tokens[i], tokens[i]] > 0:
    df.loc[tokens[i], tokens[i]] = 0

In [ ]:
df

распределить  временны́е  двухчастотного  изображение  \
распределить               0           0               0            0   
временны́е                 0           0               0            0   
двухчастотного             0           0               0            0   
изображение                0           0               0            0   
умолчание                  0           0               0            0   
...                      ...         ...             ...          ...   
таковая                    0           0               0            0   
горизонтальный             0           0               0            0   
окклюзия                   0           0               0            0   
транспортный               0           0               0            0   
высокий                    0           0               0            0   

                умолчание  прогнозирование  фильтров  ввиду  выдвигать  \
распределить            0                0         0      0          0   
временны́е              0                0         0      0          0   
двухчастотного          0                0         0      0          0   
изображение             0                0         0      0          0   
умолчание               0                0         0      0          0   
...                   ...              ...       ...    ...        ...   
таковая                 0                0         0      0          0   
горизонтальный          0                0         0      0          0   
окклюзия                0                0         0      0          0   
транспортный            0                0         0      0          0   
высокий                 0                0         0      0          0   

                расстояние  ...  ключевой  сеть  хотя  спутнико  отключение  \
распределить             0  ...         0     0     0         0           0   
временны́е               0  ...         0     0     0         0           0   
двухчастотного           0  ...         0     0     0         0           0   
изображение              0  ...         0     0     0         0           0   
умолчание                0  ...         0     0     0         0           0   
...                    ...  ...       ...   ...   ...       ...         ...   
таковая                  0  ...         0     0     0         0           0   
горизонтальный           0  ...         0     0     0         0           0   
окклюзия                 0  ...         0     0     0         0           0   
транспортный             0  ...         0     0     0         0           0   
высокий                  1  ...         1     0     0         0           0   

                таковая  горизонтальный  окклюзия  транспортный  высокий  
распределить          0               0         0             0        0  
временны́е            0               0         0             0        0  
двухчастотного        0               0         0             0        0  
изображение           0               0         0             0        0  
умолчание             0               0         0             0        0  
...                 ...             ...       ...           ...      ...  
таковая               0               0         0             0        0  
горизонтальный        0               0         0             0        0  
окклюзия              0               0         0             0        0  
транспортный          0               0         0             0        0  
высокий               0               0         0             0        0  

[1971 rows x 1971 columns]

Инициализиуем матрицу А и Aᵀ



In [ ]:
A = df.values

In [ ]:
A_T = np.transpose(A)

Посчитаем собственные значения

In [ ]:
eigen_values = np.linalg.eigvals(A * A_T)

In [ ]:
# B = np.array([[-1, 1, 0],[-1, -1, 1]])
B = np.array([[2, 6, 1],[5, 3 ,0], [2, 0, 5]])

In [ ]:
BT_B = np.dot(np.transpose(B), B)
# b = np.zeros(BT_B.shape[0])
BT_B

array([[45, 27],
       [27, 45]])

In [ ]:
eigen_values = np.linalg.eigvals(np.dot(np.transpose(B), B))
eigen_values

array([72., 18.])

In [ ]:
np.sqrt(eigen_values)

<ipython-input-262-8fdd50c435dc>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(eigen_values)


array([8.48528137, 4.24264069,        nan])

In [ ]:
# eigen_values = eigen_values[::-1]
eigen_values = np.around(eigen_values)

In [ ]:
eigen_values[eigen_values < 0] = 0
eigen_values

array([3., 2., 0.])

In [ ]:
BT_B = np.dot(np.transpose(B), B)
eigen_values = np.linalg.eigvals(BT_B)
for eigen in eigen_values:
  b = np.full(BT_B.shape[0], eigen)
  BT_Bcopy = np.copy(BT_B)
  x1 = np.linalg.solve(BT_Bcopy, b)
  print(BT_Bcopy, b, x1)

B_BT = np.dot(B, np.transpose(B))
eigen_values = np.linalg.eigvals(B_BT)
for eigen in eigen_values:
  b = np.full(B_BT.shape[0], eigen)
  B_BTcopy = np.copy(B_BT)
  x1 = np.linalg.solve(B_BTcopy, b)
  print(B_BTcopy, b, x1)

[[33 27 12]
 [27 45  6]
 [12  6 26]] [70.07123243 70.07123243 70.07123243] [0.55612089 0.92686815 2.22448357]
[[33 27 12]
 [27 45  6]
 [12  6 26]] [9.14000677 9.14000677 9.14000677] [0.07253974 0.12089956 0.29015895]
[[33 27 12]
 [27 45  6]
 [12  6 26]] [24.7887608 24.7887608 24.7887608] [0.1967362  0.32789366 0.78694479]
[[41 28  9]
 [28 34 10]
 [ 9 10 29]] [70.07123243 70.07123243 70.07123243] [0.60908479 1.006314   1.88021825]
[[41 28  9]
 [28 34 10]
 [ 9 10 29]] [9.14000677 9.14000677 9.14000677] [0.07944828 0.13126238 0.24525339]
[[41 28  9]
 [28 34 10]
 [ 9 10 29]] [24.7887608 24.7887608 24.7887608] [0.21547298 0.35599883 0.66515571]


In [ ]:
np.dot(B, np.transpose(B))

array([[ 40,  28,  -8],
       [ 28,  34, -20],
       [ -8, -20,  16]])